/*-----------------------------------------------------------------------------
FILE        : MAIN.H
INFO        : Free Superscalar Simulator
DEVELOPEMENT: GCC 2.7.0
CREATED BY  : RG[14-Oct-2025]
MODIFIED BY : XX[XX-XXX-XXXX]
-----------------------------------------------------------------------------*/
/* Automatically generated by Tool Builder Interface V1.0. */
/* File: main.h   (Don't edit this file.) */

#ifndef	__MAIN_H
#define	__MAIN_H

#include "sui.h"
#include "getopt1.h"

/*------------- GLOBAL DEFINITIONS ------------------------------------------*/
extern int verbose;
extern int debug;
extern int Tracing;
extern int ETracing;

#define MAXISSUEWIDTH	64
#define MAXWINDOWSIZE	1024
#define MAXROBSIZE	2048
#define MAXPHYSREGS	1024
#define MAXINTFU	24
#define MAXFPFU		24
#define MAXLFU		24
#define MAXSFU		24
#define MAXBFU		24
#define MAXLQSIZE	256
#define MAXSQSIZE	256
#define MAXLATENCY	10000
#define MAXITERATIONS	10000
#define MAXRSPERFU	100


typedef struct GeneralTAG
{
	char    progname[MAXFILENAMELEN];
	int     silent;
	int     interactive;
	int     batch;
	int     iterations;
	int     start_ck;
	int     tomasulo;
} General;

typedef struct ArchitectureTAG
{
	int     lregs;
	int     pregs;
	char    pipestruct[MAXFILENAMELEN];
	int     uni_lsu;
	int     load_has_pri;
	int     io_issue;
	int     io_complete;
	int     uni_di;
	int     early_rs_rel;
	int     mem_pipe;
	int     f_width;
	int     d_width;
	int     p_width;
	int     i_width;
	int     w_width;
	int     c_width;
	int     win_size;
	int     rob_size;
	int     int_fu;
	int     a_lat;
	int     a_rs;
	int     im_fu;
	int     im_lat;
	int     im_pipe;
	int     im_rs;
	int     id_fu;
	int     id_lat;
	int     id_pipe;
	int     id_rs;
	int     fp_fu;
	int     fm_fu;
	int     l_fu;
	int     l_lat;
	int     l_pipe;
	int     s_fu;
	int     s_lat;
	int     s_pipe;
	int     s_waits;
	int     ls_rs;
	int     b_fu;
	int     b_lat;
	int     b_rs;
	int     lqsize;
	int     sqsize;
	int     speculation;
	int     wblat;
} Architecture;

typedef struct Program_DefaultsTAG
{
	char    logfile[MAXFILENAMELEN];
} Program_Defaults;


extern  General				G;
extern  Architecture			AA;
extern  Program_Defaults		Pro;

#endif  /* __MAIN_H */


